server {
    listen       80;
    server_name  localhost air.uat.redair.cn *.redair.cn *.a6air.com *.tcair.com;
        root    /etc/nginx/conf.d;
        location /smartAiMng/ {
                add_header Cache-Control 'no-cache, must-revalidate, proxy-revalidate, max-age=0';
  index  index.html;
  try_files $uri $uri/ /smartAiMng/index.html;
    }
}

server {
    listen       80;
    server_name  127.0.0.1;
        location /monitor.jsp {
                default_type text/plain;
                return 200 '1';
        }
}